phases:
  install:
    commands:
      - echo "Listing files to verify package.json location"
      - ls -R
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo Running tests...
      - npm test
artifacts:
  files:
    - '**/*'
  discard-paths: yes
